var CU=requireUser();var CP=requireProject();
var npT=null,npV='',npD=true;var CACHE={adjs:[]};
buildHeader({title:t('adj'),role:'user',showLang:true});
function applyTR(){setText('hdr-title',t('adj'));setText('t-adjdesc',t('adjD'));setText('t-addline',t('addL'));if(G('t-back2'))G('t-back2').textContent=t('back');if(G('t-next2'))G('t-next2').textContent=t('next');refreshAdjs();}
applyTR();
function loadAdjs(){return dbGetAdjs(CP.id).then(function(a){CACHE.adjs=a;return a;});}
function addAdj(){sb.from('adjustments').insert({project_id:CP.id,description:'',type:'+',amount:0}).then(function(){loadAdjs().then(refreshAdjs);});}
function refreshAdjs(){var adjs=CACHE.adjs;var list=G('adj-list');if(!list)return;list.innerHTML='';adjs.forEach(function(a){var div=document.createElement('div');div.className='adj-item';var row=document.createElement('div');row.className='adj-row';var sg=document.createElement('button');sg.className='adj-sign';sg.style.background=a.type==='+'?'#e8f5ee':'#ffeaea';sg.style.color=a.type==='+'?'#1a7a4a':'#d63031';sg.textContent=a.type;sg.onclick=function(){var nt=a.type==='+'?'-':'+';sb.from('adjustments').update({type:nt}).eq('id',a.id).then(function(){a.type=nt;loadAdjs().then(refreshAdjs);});};var inp=document.createElement('input');inp.type='text';inp.className='inp';inp.placeholder=t('adj');inp.value=a.description||'';inp.style.cssText='flex:1;margin-bottom:0';inp.onchange=function(){sb.from('adjustments').update({description:this.value}).eq('id',a.id).then(function(){});};var db=document.createElement('button');db.style.cssText='width:34px;height:34px;background:transparent;border:none;color:#d63031;font-size:18px;flex-shrink:0;cursor:pointer';db.textContent='✕';db.onclick=function(){sb.from('adjustments').delete().eq('id',a.id).then(function(){loadAdjs().then(refreshAdjs);});};row.appendChild(sg);row.appendChild(inp);row.appendChild(db);var nf=document.createElement('div');nf.className='num-field';var nl=document.createElement('span');nl.className='nf-label';nl.textContent=t('adj');var nv=document.createElement('span');var am=parseFloat(a.amount)||0;nv.className=am>0?'nf-val':'nf-ph';nv.textContent=am>0?am.toFixed(2)+' DH':t('tap');nf.appendChild(nl);nf.appendChild(nv);nf.onclick=function(){openNP('adj_'+a.id,t('adj'),true);};div.appendChild(row);div.appendChild(nf);list.appendChild(div);});}
function openNP(target,label,decimal){npT=target;npD=(decimal!==false);npV='';setText('np-lbl',label||'');G('np-disp').textContent='0';var db=G('np-dot-btn');if(db)db.style.display=npD?'block':'none';var grid=G('np-grid');if(grid){grid.innerHTML='';['7','8','9','4','5','6','1','2','3','C','0','⌫'].forEach(function(k){var b=document.createElement('button');b.className='nk'+(k==='C'?' nk-c':'');b.textContent=k;b.onclick=function(){if(k==='C')npV='';else if(k==='⌫')npV=npV.slice(0,-1);else npV+=k;G('np-disp').textContent=npV||'0';};grid.appendChild(b);});}show('np-ov');}
function npDot(){if(npV.indexOf('.')<0){npV+='.';G('np-disp').textContent=npV||'0';}}
function closeNP(){hide('np-ov');npT=null;npV='';}
function confirmNP(){var v=parseFloat(npV)||0,tgt=npT;closeNP();if(tgt&&tgt.indexOf('adj_')===0){var aid=tgt.slice(4);sb.from('adjustments').update({amount:v}).eq('id',aid).then(function(){loadAdjs().then(refreshAdjs);});}}
loadAdjs().then(refreshAdjs);
