var CU=requireAdmin();var CACHE={products:[]};
buildHeader({title:'Database',role:'admin',activeTab:'database'});
function loadProducts(){return dbGetProducts().then(function(p){CACHE.products=p;return p;});}
<<<<<<< HEAD
function refreshDB(){loadProducts().then(function(p){renderDBTable(p);});}
=======
function refreshDB(){loadProducts().then(function(p){setText('db-pc',String(p.length));renderDBTable(p);});dbGetUsers().then(function(u){setText('db-uc',String(u.length));});dbGetProjects(CU.id).then(function(pr){setText('db-prc',String(pr.length));});}
>>>>>>> b431d67383dde2c022f7a4f776f603a97d6d6512
function renderDBTable(prods){var tb=G('db-all-tbody');if(!tb)return;tb.innerHTML='';prods.forEach(function(p){var tr=document.createElement('tr');var c1=document.createElement('td');c1.style.cssText='font-family:monospace;font-size:12px;color:#888';c1.textContent=p.barcode||'—';var c2=document.createElement('td');c2.textContent=p.name||'—';var c3=document.createElement('td');c3.style.cssText='text-align:right;font-weight:600;color:#1a7a4a;white-space:nowrap';c3.textContent=(parseFloat(p.price)||0).toFixed(2)+' DH';var c4=document.createElement('td');c4.style.whiteSpace='nowrap';var eb=document.createElement('button');eb.className='btn-b';eb.style.cssText='padding:4px 7px;font-size:12px;margin-right:3px';eb.textContent='✏️';eb.onclick=function(){var n=prompt('Name:',p.name);var pr2=prompt('Price (DH):',String(p.price));if(n&&pr2!=null){sb.from('products').update({name:n.trim(),price:parseFloat(pr2)||0}).eq('id',p.id).then(function(){refreshDB();showToast('✅');});}};var db=document.createElement('button');db.className='btn-r';db.style.cssText='padding:4px 7px;font-size:12px';db.textContent='🗑';db.onclick=function(){if(!confirm('Delete?'))return;sb.from('products').delete().eq('id',p.id).then(function(){refreshDB();showToast('✅');});};c4.appendChild(eb);c4.appendChild(db);tr.appendChild(c1);tr.appendChild(c2);tr.appendChild(c3);tr.appendChild(c4);tb.appendChild(tr);});}
function dbSearch(q){var res=G('db-results');if(!res)return;res.innerHTML='';if(!q||!q.trim())return;var f=CACHE.products.filter(function(p){return (p.name||'').toLowerCase().indexOf(q.toLowerCase())>=0||(p.barcode||'').indexOf(q)>=0;}).slice(0,15);if(!f.length){res.innerHTML='<p style="font-size:13px;color:#888;padding:8px 0">No results</p>';return;}f.forEach(function(p){var row=document.createElement('div');row.style.cssText='display:flex;align-items:center;justify-content:space-between;padding:8px 0;border-bottom:.5px solid #e0e0e0;gap:8px';var info=document.createElement('div');info.style.flex='1';info.innerHTML='<p style="font-size:14px;font-weight:500;margin:0 0 1px">'+esc(p.name)+'</p><p style="font-size:11px;color:#888;margin:0">'+(p.barcode||'')+'</p>';var pe=document.createElement('strong');pe.style.cssText='color:#1a7a4a;font-size:14px;white-space:nowrap';pe.textContent=(parseFloat(p.price)||0).toFixed(2)+' DH';var eb=document.createElement('button');eb.className='btn-b';eb.style.marginLeft='4px';eb.textContent='✏️';eb.onclick=function(){var n=prompt('Name:',p.name);var pr2=prompt('Price:',String(p.price));if(n&&pr2!=null){sb.from('products').update({name:n.trim(),price:parseFloat(pr2)||0}).eq('id',p.id).then(function(){pe.textContent=(parseFloat(pr2)||0).toFixed(2)+' DH';loadProducts();showToast('✅');});}};var db=document.createElement('button');db.className='btn-r';db.style.marginLeft='4px';db.textContent='🗑';db.onclick=function(){if(!confirm('Delete?'))return;sb.from('products').delete().eq('id',p.id).then(function(){if(row.parentNode)row.parentNode.removeChild(row);loadProducts();refreshDB();showToast('✅');});};var btns=document.createElement('div');btns.style.cssText='display:flex;align-items:center';btns.appendChild(pe);btns.appendChild(eb);btns.appendChild(db);row.appendChild(info);row.appendChild(btns);res.appendChild(row);});}
function toggleAddForm(){var f=G('db-add-form');if(!f)return;f.classList.toggle('hidden');if(!f.classList.contains('hidden')){var b=G('db-bc');if(b)b.focus();}}
function dbAddProd(){var bc=(G('db-bc')?G('db-bc').value||'':'').trim();var nm=(G('db-nm')?G('db-nm').value||'':'').trim();var pr=parseFloat(G('db-pr')?G('db-pr').value||'0':'0')||0;if(!nm){showToast('❌ Name required');return;}sb.from('products').insert({barcode:bc,name:nm,price:pr}).then(function(r){if(r.error){showToast('❌ '+r.error.message);return;}if(G('db-bc'))G('db-bc').value='';if(G('db-nm'))G('db-nm').value='';if(G('db-pr'))G('db-pr').value='';showToast('✅ Added: '+nm);refreshDB();});}
function importCSV(file){if(!file)return;var reader=new FileReader();reader.onload=function(e){var text=e.target.result||'';var lines=text.split(/\r\n|\n|\r/);var rows=[];var start=0;if(lines.length>0){var h=lines[0].toLowerCase();if(h.indexOf('barcode')>=0||h.indexOf('code')>=0||h.indexOf('name')>=0||h.indexOf('nom')>=0||h.indexOf('price')>=0||h.indexOf('prix')>=0)start=1;}for(var i=start;i<lines.length;i++){var line=lines[i].trim();if(!line)continue;var cols=line.split(/[,;]/);if(cols.length<2)continue;var bc=(cols[0]||'').trim().replace(/^"|"$/g,'');var nm=(cols[1]||'').trim().replace(/^"|"$/g,'');var pr=parseFloat((cols[2]||'0').trim().replace(/^"|"$/g,'').replace(',','.'))||0;if(!nm)continue;rows.push({barcode:bc,name:nm,price:pr});}if(!rows.length){showToast('❌ CSV invalide');return;}showToast('⏳ Import…');sb.from('products').insert(rows).then(function(r){if(r.error){showToast('❌ '+r.error.message,4000);return;}showToast('✅ '+rows.length+' produits ajoutés',4000);refreshDB();});var fi=G('csv-file');if(fi)fi.value='';};reader.readAsText(file);}
refreshDB();
