var CU=requireUser();var CP=requireProject();
var CACHE={items:[],adjs:[]};
<<<<<<< HEAD
buildHeader({title:t('recap'),role:'user',showLang:true});
function applyTR(){setText('hdr-title',t('recap'));setText('t-prods-title',t('prods'));setText('t-adjs-title',t('adj'));setText('t-totalp',t('tP'));setText('t-totala',t('tA'));setText('t-summp',t('tP'));setText('t-summa',t('tA'));setText('t-grand',t('grand'));setText('t-dlpdf',t('dlPDF'));setText('t-newinv',t('nInv'));if(G('t-back3'))G('t-back3').textContent=t('back');refreshRecap();}
applyTR();
function refreshRecap(){var items=CACHE.items,adjs=CACHE.adjs;var tP=items.reduce(function(s,p){return s+(parseFloat(p.price)||0)*(parseFloat(p.quantity)||0);},0);var tA=adjs.reduce(function(s,a){return s+(a.type==='+'?1:-1)*(parseFloat(a.amount)||0);},0);var grand=tP+tA;var pb=G('recap-ptbody');if(pb){pb.innerHTML='';items.forEach(function(p,i){var pr=parseFloat(p.price)||0,q=parseFloat(p.quantity)||0;var tr=document.createElement('tr');tr.innerHTML='<td style="text-align:center;color:#888;font-size:11px">'+(i+1)+'</td><td>'+esc(p.name||'—')+'</td><td style="text-align:right">'+pr.toFixed(2)+'</td><td style="text-align:center">'+q+'</td><td style="text-align:right;font-weight:600">'+fmt(pr*q)+'</td>';pb.appendChild(tr);});}setText('recap-totalp',fmt(tP));var ac=G('recap-acard');if(adjs.length>0){if(ac)ac.classList.remove('hidden');var ab=G('recap-atbody');if(ab){ab.innerHTML='';adjs.forEach(function(a){var ap=parseFloat(a.amount)||0,col=a.type==='+'?'#1a7a4a':'#d63031';var tr=document.createElement('tr');tr.innerHTML='<td>'+esc(a.description||'—')+'</td><td style="text-align:center;color:'+col+';font-weight:700">'+a.type+'</td><td style="text-align:right;color:'+col+';font-weight:700">'+(a.type==='+'?'+':'-')+ap.toFixed(2)+' DH</td>';ab.appendChild(tr);});}setText('recap-totala',(tA>=0?'+':'')+fmt(tA));show('summ-arow');var av=G('summ-a');if(av){av.textContent=(tA>=0?'+':'')+fmt(tA);av.style.color=tA>=0?'#1a7a4a':'#d63031';}}else{if(ac)ac.classList.add('hidden');hide('summ-arow');}setText('summ-p',fmt(tP));setText('grand-val',fmt(grand));}
function genPDF(){generatePDF(CP,CACHE.items,CACHE.adjs,CU.fullname||CU.username);}
function newInv(){if(!confirm(t('nInvQ')))return;clearCurrentProject();location.href='inventory.html';}
=======
function t(k){var m={adj:'Ajustements',recap:'Récapitulatif'};return m[k]||k;}
buildHeader({title:'Récapitulatif',role:'user',showLang:false});
function refreshRecap(){var items=CACHE.items,adjs=CACHE.adjs;var tP=items.reduce(function(s,p){return s+(parseFloat(p.price)||0)*(parseFloat(p.quantity)||0);},0);var tA=adjs.reduce(function(s,a){return s+(a.type==='+'?1:-1)*(parseFloat(a.amount)||0);},0);var grand=tP+tA;var pb=G('recap-ptbody');if(pb){pb.innerHTML='';items.forEach(function(p,i){var pr=parseFloat(p.price)||0,q=parseFloat(p.quantity)||0;var tr=document.createElement('tr');tr.innerHTML='<td style="text-align:center;color:#888;font-size:11px">'+(i+1)+'</td><td>'+esc(p.name||'—')+'</td><td style="text-align:right">'+pr.toFixed(2)+'</td><td style="text-align:center">'+q+'</td><td style="text-align:right;font-weight:600">'+fmt(pr*q)+'</td>';pb.appendChild(tr);});}setText('recap-totalp',fmt(tP));var ac=G('recap-acard');if(adjs.length>0){if(ac)ac.classList.remove('hidden');var ab=G('recap-atbody');if(ab){ab.innerHTML='';adjs.forEach(function(a){var ap=parseFloat(a.amount)||0,col=a.type==='+'?'#1a7a4a':'#d63031';var tr=document.createElement('tr');tr.innerHTML='<td>'+esc(a.description||'—')+'</td><td style="text-align:center;color:'+col+';font-weight:700">'+a.type+'</td><td style="text-align:right;color:'+col+';font-weight:700">'+(a.type==='+'?'+':'-')+ap.toFixed(2)+' DH</td>';ab.appendChild(tr);});}setText('recap-totala',(tA>=0?'+':'')+fmt(tA));show('summ-arow');var av=G('summ-a');if(av){av.textContent=(tA>=0?'+':'')+fmt(tA);av.style.color=tA>=0?'#1a7a4a':'#d63031';}}else{if(ac)ac.classList.add('hidden');hide('summ-arow');}setText('summ-p',fmt(tP));setText('grand-val',fmt(grand));}
function genPDF(){generatePDF(CP,CACHE.items,CACHE.adjs,CU.fullname||CU.username);}
function newInv(){if(!confirm('Recommencer ?'))return;clearCurrentProject();location.href='inventory.html';}
>>>>>>> b431d67383dde2c022f7a4f776f603a97d6d6512
Promise.all([dbGetItems(CP.id),dbGetAdjs(CP.id)]).then(function(r){CACHE.items=r[0];CACHE.adjs=r[1];refreshRecap();});
