// ====== ADMIN PANEL ======
var CU=requireAdmin(); // redirects if not admin
var CACHE={products:[]};var lang='en';
function isAr(){return false;}
function t(k){var m={rUsr:'User',rAdm:'Administrator',upd:'Update',prof:'My profile'};return m[k]||k;}
function setAvatar(){var av=G('hdr-av');if(av)av.textContent=(CU.fullname||CU.username)[0].toUpperCase();setText('av-name',CU.fullname||CU.username);setText('av-role','Administrator');}
function toggleAvMenu(){G('av-menu').classList.toggle('show');}
function goProf(){G('av-menu').classList.remove('show');showPage('profile');}
function backToApp(){showPage('database');}
document.addEventListener('click',function(e){var m=G('av-menu');if(m&&m.classList.contains('show')){if(!e.target.closest('#av-menu')&&!e.target.closest('#hdr-av'))m.classList.remove('show');}});
function loadProducts(){return dbGetProducts().then(function(p){CACHE.products=p;return p;});}
function showPage(name){var pages=['database','users','profile'];pages.forEach(function(p){var el=G('pg-'+p);if(el){if(p===name)el.classList.add('active');else el.classList.remove('active');}});var titles={database:'Database',users:'Users',profile:'My profile'};setText('hdr-title',titles[name]||name);var td=G('tab-database'),tu=G('tab-users');if(td)td.classList.toggle('active',name==='database');if(tu)tu.classList.toggle('active',name==='users');var bc=G('back-to-app-card');if(bc){if(name==='profile')bc.classList.remove('hidden');else bc.classList.add('hidden');}if(name==='database')refreshDB();if(name==='users')refreshUsers();if(name==='profile')refreshProfile();}

// ---- USERS ----
function refreshUsers(){
  var tb=G('users-tbody');if(!tb)return;tb.innerHTML='<tr><td colspan="4" style="color:#666;padding:10px">…</td></tr>';
  dbGetUsers().then(function(users){
    setText('db-uc',String(users.length));tb.innerHTML='';
    users.forEach(function(u){
      var tr=document.createElement('tr');
      var av=document.createElement('div');av.style.cssText='width:28px;height:28px;border-radius:50%;background:'+(u.color||'#1a7a4a')+';color:#fff;display:flex;align-items:center;justify-content:center;font-weight:700;font-size:11px;flex-shrink:0';av.textContent=(u.fullname||u.username)[0].toUpperCase();
      var td1=document.createElement('td');td1.style.cssText='display:flex;align-items:center;gap:8px;padding:10px 8px';var w=document.createElement('div');w.innerHTML='<div style="font-weight:600">'+esc(u.username)+'</div>'+(u.fullname&&u.fullname!==u.username?'<div style="font-size:11px;color:#888">'+esc(u.fullname)+'</div>':'');td1.appendChild(av);td1.appendChild(w);
      var td2=document.createElement('td');var bd=document.createElement('span');bd.className=u.role==='admin'?'badge b-admin':'badge b-user';bd.textContent=u.role==='admin'?'Administrator':'User';td2.appendChild(bd);
      var td3=document.createElement('td');td3.style.cssText='color:#999;font-size:12px';td3.textContent='••••';
      var td4=document.createElement('td');
      var eb=document.createElement('button');eb.className='btn-b';eb.style.marginRight='4px';eb.textContent='✏️';
      eb.onclick=function(){var nf=prompt('Full name:',u.fullname||'');var np=prompt('New PIN (6 digits, empty=keep):','');var upd={};if(nf!=null)upd.fullname=nf.trim();function done(){sb.from('app_users').update(upd).eq('id',u.id).then(function(){showToast('✅ Updated');refreshUsers();});}if(np&&np.length===6){hashPIN(np).then(function(h){upd.pin_hash=h;done();});}else done();};
      var db=document.createElement('button');db.className='btn-r';db.textContent='🗑';
      if(u.role==='admin'||u.id===CU.id){db.disabled=true;db.style.opacity='.4';}
      else db.onclick=function(){if(!confirm('Delete this user?'))return;sb.from('app_users').delete().eq('id',u.id).then(function(){showToast('✅ Deleted');refreshUsers();});};
      td4.appendChild(eb);td4.appendChild(db);tr.appendChild(td1);tr.appendChild(td2);tr.appendChild(td3);tr.appendChild(td4);tb.appendChild(tr);
    });
  });
}
function doCreateUser(){
  var name=(G('new-uname')?G('new-uname').value||'':'').trim();var full=(G('new-ufull')?G('new-ufull').value||'':'').trim();var pin=(G('new-upin')?G('new-upin').value||'':'').trim();var role=(G('new-urole')?G('new-urole').value:'user');var err=G('user-err');
  if(!name||pin.length!==6){if(err){err.textContent='Username and 6-digit PIN required';err.classList.remove('hidden');}return;}
  dbGetUserByUsername(name).then(function(ex){
    if(ex){if(err){err.textContent='User already exists';err.classList.remove('hidden');}return;}
    var cols=['#1a7a4a','#2563eb','#7c3aed','#d63031','#f59e0b','#0891b2','#059669'];
    hashPIN(pin).then(function(h){sb.from('app_users').insert({username:name,fullname:full||name,role:role,pin_hash:h,color:cols[Math.floor(Math.random()*cols.length)]}).then(function(r){if(r.error){if(err){err.textContent=r.error.message;err.classList.remove('hidden');}return;}if(G('new-uname'))G('new-uname').value='';if(G('new-ufull'))G('new-ufull').value='';if(G('new-upin'))G('new-upin').value='';if(err)err.classList.add('hidden');showToast('✅ Created: '+name);refreshUsers();});});
  });
}
// ---- DATABASE ----
function refreshDB(){loadProducts().then(function(p){setText('db-pc',String(p.length));renderDBTable(p);});dbGetUsers().then(function(u){setText('db-uc',String(u.length));});dbGetProjects(CU.id).then(function(pr){setText('db-prc',String(pr.length));});}
function renderDBTable(prods){var tb=G('db-all-tbody');if(!tb)return;tb.innerHTML='';prods.forEach(function(p){var tr=document.createElement('tr');var c1=document.createElement('td');c1.style.cssText='font-family:monospace;font-size:12px;color:#666';c1.textContent=p.barcode||'—';var c2=document.createElement('td');c2.textContent=p.name||'—';var c3=document.createElement('td');c3.style.cssText='text-align:right;font-weight:600;color:#1a7a4a;white-space:nowrap';c3.textContent=(parseFloat(p.price)||0).toFixed(2)+' DH';var c4=document.createElement('td');c4.style.whiteSpace='nowrap';var eb=document.createElement('button');eb.className='btn-b';eb.style.cssText='padding:4px 7px;font-size:12px;margin-right:3px';eb.textContent='✏️';eb.onclick=function(){var n=prompt('Name:',p.name);var pr2=prompt('Price (DH):',String(p.price));if(n&&pr2!=null){sb.from('products').update({name:n.trim(),price:parseFloat(pr2)||0}).eq('id',p.id).then(function(){refreshDB();showToast('✅');});}};var db=document.createElement('button');db.className='btn-r';db.style.cssText='padding:4px 7px;font-size:12px';db.textContent='🗑';db.onclick=function(){if(!confirm('Delete?'))return;sb.from('products').delete().eq('id',p.id).then(function(){refreshDB();showToast('✅');});};c4.appendChild(eb);c4.appendChild(db);tr.appendChild(c1);tr.appendChild(c2);tr.appendChild(c3);tr.appendChild(c4);tb.appendChild(tr);});}
function dbSearch(q){var res=G('db-results');if(!res)return;res.innerHTML='';if(!q||!q.trim())return;var prods=CACHE.products;var f=prods.filter(function(p){return (p.name||'').toLowerCase().indexOf(q.toLowerCase())>=0||(p.barcode||'').indexOf(q)>=0;}).slice(0,15);if(!f.length){res.innerHTML='<p style="font-size:13px;color:#666;padding:8px 0">No results</p>';return;}f.forEach(function(p){var row=document.createElement('div');row.style.cssText='display:flex;align-items:center;justify-content:space-between;padding:8px 0;border-bottom:.5px solid #e0e0e0;gap:8px';var info=document.createElement('div');info.style.flex='1';info.innerHTML='<p style="font-size:14px;font-weight:500;margin:0 0 1px">'+esc(p.name)+'</p><p style="font-size:11px;color:#666;margin:0">'+(p.barcode||'')+'</p>';var pe=document.createElement('strong');pe.style.cssText='color:#1a7a4a;font-size:14px;white-space:nowrap';pe.textContent=(parseFloat(p.price)||0).toFixed(2)+' DH';var eb=document.createElement('button');eb.className='btn-b';eb.style.marginLeft='4px';eb.textContent='✏️';eb.onclick=function(){var n=prompt('Name:',p.name);var pr2=prompt('Price:',String(p.price));if(n&&pr2!=null){sb.from('products').update({name:n.trim(),price:parseFloat(pr2)||0}).eq('id',p.id).then(function(){pe.textContent=(parseFloat(pr2)||0).toFixed(2)+' DH';loadProducts();showToast('✅');});}};var db=document.createElement('button');db.className='btn-r';db.style.marginLeft='4px';db.textContent='🗑';db.onclick=function(){if(!confirm('Delete?'))return;sb.from('products').delete().eq('id',p.id).then(function(){if(row.parentNode)row.parentNode.removeChild(row);loadProducts();refreshDB();showToast('✅');});};var btns=document.createElement('div');btns.style.cssText='display:flex;align-items:center';btns.appendChild(pe);btns.appendChild(eb);btns.appendChild(db);row.appendChild(info);row.appendChild(btns);res.appendChild(row);});}
function toggleAddForm(){var f=G('db-add-form');if(!f)return;f.classList.toggle('hidden');if(!f.classList.contains('hidden')){var b=G('db-bc');if(b)b.focus();}}
function dbAddProd(){var bc=(G('db-bc')?G('db-bc').value||'':'').trim();var nm=(G('db-nm')?G('db-nm').value||'':'').trim();var pr=parseFloat(G('db-pr')?G('db-pr').value||'0':'0')||0;if(!nm){showToast('❌ Name required');return;}sb.from('products').insert({barcode:bc,name:nm,price:pr}).then(function(r){if(r.error){showToast('❌ '+r.error.message);return;}if(G('db-bc'))G('db-bc').value='';if(G('db-nm'))G('db-nm').value='';if(G('db-pr'))G('db-pr').value='';showToast('✅ Added: '+nm);refreshDB();});}
function importCSV(file){if(!file)return;var reader=new FileReader();reader.onload=function(e){var text=e.target.result||'';var lines=text.split(/\r\n|\n|\r/);var rows=[];var start=0;if(lines.length>0){var h=lines[0].toLowerCase();if(h.indexOf('barcode')>=0||h.indexOf('code')>=0||h.indexOf('name')>=0||h.indexOf('nom')>=0||h.indexOf('price')>=0||h.indexOf('prix')>=0)start=1;}for(var i=start;i<lines.length;i++){var line=lines[i].trim();if(!line)continue;var cols=line.split(/[,;]/);if(cols.length<2)continue;var bc=(cols[0]||'').trim().replace(/^"|"$/g,'');var nm=(cols[1]||'').trim().replace(/^"|"$/g,'');var pr=parseFloat((cols[2]||'0').trim().replace(/^"|"$/g,'').replace(',','.'))||0;if(!nm)continue;rows.push({barcode:bc,name:nm,price:pr});}if(!rows.length){showToast('❌ CSV invalide');return;}showToast('⏳ Import…');sb.from('products').insert(rows).then(function(r){if(r.error){showToast('❌ '+r.error.message,4000);return;}showToast('✅ '+rows.length+' produits ajoutés',4000);refreshDB();});var fi=G('csv-file');if(fi)fi.value='';};reader.readAsText(file);}
// ---- PROFILE ----
function refreshProfile(){var av=G('prof-av');if(av){av.textContent=(CU.fullname||CU.username)[0].toUpperCase();av.style.background=CU.color||'#1a7a4a';}setText('prof-name',CU.fullname||CU.username);var bd=G('prof-badge');if(bd){bd.textContent='Administrator';bd.className='badge b-admin';}var ni=G('prof-newname');if(ni)ni.value=CU.fullname||CU.username;}
function updateProf(type){if(type==='name'){var n=(G('prof-newname')?G('prof-newname').value||'':'').trim();if(!n)return;sb.from('app_users').update({fullname:n}).eq('id',CU.id).then(function(){CU.fullname=n;setSession(CU);setAvatar();showToast('✅ Updated');refreshProfile();});}else{var p=(G('prof-newpin')?G('prof-newpin').value||'':'');var c=(G('prof-confpin')?G('prof-confpin').value||'':'');if(p.length!==6){showToast('❌ PIN 6 digits');return;}if(p!==c){showToast('❌ PIN mismatch');return;}hashPIN(p).then(function(h){sb.from('app_users').update({pin_hash:h}).eq('id',CU.id).then(function(){if(G('prof-newpin'))G('prof-newpin').value='';if(G('prof-confpin'))G('prof-confpin').value='';showToast('✅ PIN updated');});});}}
// ---- INIT ----
setAvatar();showPage('database');
